name: Canary release on new commit
on:
  push:
    branches:
      - develop

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run build

      - name: Extract short commit ID
        run: echo "::set-env name=SHORT_COMMIT_ID::$(git log -1 --pretty=format:%h)"

      - name: Set package version
        run: echo "VERSION=canary-${{ env.SHORT_COMMIT_ID }}" >> $GITHUB_ENV
        
      - name: Canary release to npm
        run: |
          npm publish --access public --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          VERSION: ${{ env.VERSION }}
